import type { Metadata } from 'next';
import './globals.css';
import TheNavbar from '@/components/TheNavbar';
import TheFooter from '@/components/TheFooter';
import LenisProvider from '../providers/LenisProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <LenisProvider>
          <TheNavbar />
          {children}
          <TheFooter />
        </LenisProvider>
      </body>
    </html>
  );
}
